# ----------------------------------------
# 1. Conexión a MySQL (Nodo 1 - Local)
# ----------------------------------------
# Asegúrate de que el nombre de la BD sea donde hicimos las vistas
spring.datasource.url=jdbc:mysql://localhost:3306/socialnet_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=040313
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ----------------------------------------
# 2. Conexión a MongoDB (Nodo 2 - Red)
# ----------------------------------------
# Aquí Spring Boot viaja por ZeroTier para buscar las publicaciones
spring.data.mongodb.uri=mongodb://172.25.219.232:27017/socialnet_db

# ----------------------------------------
# 3. Configuración de JPA / Hibernate
# ----------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
